In [1]:
list= [1,2,3,4]

In [1]:
import numpy as np

In [8]:
arr = np.array(list)

In [6]:
arr

array([1, 2, 3, 4])

In [11]:
my_mat = [[1,3],[4,6],[7,9]]

In [12]:
mat = np.array(my_mat)

In [13]:
mat

array([[1, 3],
       [4, 6],
       [7, 9]])

In [14]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,100,2)    #1D array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [17]:

np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,10,20)   #1D array (srt value, end value , no. of ele)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
np.eye(5)   #identity matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.   #tab to show more methods

SyntaxError: invalid syntax (<ipython-input-22-0d197dd68053>, line 1)

In [23]:
np.random.rand(10)      #1D  #random uniform distributed no.s form 0 to 1

array([0.28026565, 0.16787305, 0.48463197, 0.05403231, 0.38281919,
       0.96425495, 0.22624702, 0.51933447, 0.54396709, 0.92340162])

In [24]:
np.random.rand(4,3)     #2D

array([[0.71044966, 0.69782761, 0.32222729],
       [0.98379767, 0.50630718, 0.63154824],
       [0.66804303, 0.01926958, 0.42948618],
       [0.77428838, 0.4390071 , 0.06710739]])

In [25]:
np.random.randn(10)  #1D  #normal distribution centered around zero

array([-1.31797674,  0.8629503 ,  0.19236813,  0.49612644, -0.07385473,
       -1.16931105,  0.56865083,  0.41693572, -0.24433347,  0.82332624])

In [26]:
np.random.randn(4,3)    #2D

array([[-0.15316761, -1.06499944,  0.43885958],
       [-0.69602353,  0.3837331 ,  0.79547097],
       [ 1.40146011, -0.18912642, -0.55929664],
       [ 0.91858222, -1.03779765, -0.31208239]])

In [27]:
np.random.randint(1,100)   #1 random integer  #1 is inclusive but 100 exclusive

22

In [2]:
ranarr = np.random.randint(1,100,20)     #20 random int  #1 is inclusive but 100 exclusive

In [3]:
ranarr

array([ 5, 37,  9, 59, 28, 80, 29,  7, 76, 53, 49, 29, 99, 82, 96, 82, 71,
       11, 56, 64])

In [4]:
ranarr1 =  ranarr.reshape(5,4)     #return same data with new shapef

In [5]:
ranarr1

array([[ 5, 37,  9, 59],
       [28, 80, 29,  7],
       [76, 53, 49, 29],
       [99, 82, 96, 82],
       [71, 11, 56, 64]])

In [4]:
arr1 = np.arange(24)

In [5]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
arr2  =arr1.reshape(2,4,3)   #3D array (2 layers each layer with 2D array of 4*3 matrix)

In [17]:
arr2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [18]:
arr2.transpose(2,0,1)                  # 3 layers of 2*4 matrix

array([[[ 0,  3,  6,  9],
        [12, 15, 18, 21]],

       [[ 1,  4,  7, 10],
        [13, 16, 19, 22]],

       [[ 2,  5,  8, 11],
        [14, 17, 20, 23]]])

In [13]:
arr1.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
arr2.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [ ]:
arr2.transpose

In [12]:
ranarr1  

array([[ 5, 37,  9, 59],
       [28, 80, 29,  7],
       [76, 53, 49, 29],
       [99, 82, 96, 82],
       [71, 11, 56, 64]])

In [13]:
ranarr.min()

5

In [14]:
ranarr.max()

99

In [15]:
ranarr.argmin()   #index location of min value

0

In [16]:
ranarr.argmax()   #index location of max value

12

In [56]:
ranarr.shape      #1 D array with 20 ele

(20,)

In [57]:
ranarr1.shape      #2D array of 5,4 matrix

(5, 4)

In [58]:
ranarr.dtype       # this means 32 bit integers

dtype('int32')

In [59]:
ranarr1.dtype

dtype('int32')

In [60]:
from numpy.random import randint

In [61]:
randint(2,10)

7

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[8]

8

In [12]:
arr[1:7]          #slice notation

array([1, 2, 3, 4, 5, 6])

In [13]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [14]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[2:7] =99     # numpy array is diff from nrml list because of there ability to broadcast

In [16]:
arr

array([ 0,  1, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [17]:
arr = np.arange(0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr 

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:] =98       #also cnge in original

In [22]:
arr

array([98, 98, 98, 98, 98, 98,  6,  7,  8,  9, 10])

In [29]:
slice_of_arr

array([98, 98, 98, 98, 98, 98])

In [30]:
arr_copy =arr.copy()

In [31]:
arr_copy

array([98, 98, 98, 98, 98, 98,  6,  7,  8,  9, 10])

In [32]:
arr_copy[:] = 100

In [33]:
arr_copy            #this only changes in the copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [34]:
arr               #no cnge in original

array([98, 98, 98, 98, 98, 98,  6,  7,  8,  9, 10])

In [77]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [78]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [79]:
arr_2d[1]

array([20, 25, 30])

In [82]:
arr_2d[:,1]          # but this is only one dimentional

array([10, 25, 40])

In [84]:
arr_2d[:,1:2]        #this is in 2D

array([[10],
       [25],
       [40]])

In [8]:
arr_2d[2,1]       #single bracket notation  

40

In [9]:
arr_2d[2][1]      #double bracket notation

40

In [16]:
arr_2d[1:,:2]    #slice notation

array([[20, 25],
       [35, 40]])

In [42]:
arr =np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
bool_arr = arr >5        #comparing to get boolean array

In [45]:
bool_arr 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [46]:
arr[bool_arr]     #conditional selection where bool_array is true

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr<7]        #shortcut 

array([1, 2, 3, 4, 5, 6])

In [48]:
arr[arr<3]

array([1, 2])

In [49]:
arr_2d = np.arange(0,50).reshape(5,10)

In [50]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# Numpy operations

#### array with array

In [53]:
arr = np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [56]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### array with scalars

In [59]:
arr +50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [60]:
1/0

ZeroDivisionError: division by zero

In [61]:
arr/arr

<ipython-input-61-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
1/arr

<ipython-input-62-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [65]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

#### universal array funcions

In [69]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [70]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [71]:
np.max(arr)

10

In [73]:
arr.max()

10

In [74]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [75]:
np.log(arr)

<ipython-input-75-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])